2025-03-31 23:34:45,082 - __main__ - INFO - Логирование настроено успешно
2025-03-31 23:34:45,082 - __main__ - INFO - ==================== ЗАПУСК БОТА ====================
2025-03-31 23:34:45,082 - __main__ - INFO - Токен бота: 75134...Qy0E
2025-03-31 23:34:45,330 - __main__ - INFO - Все обработчики зарегистрированы
2025-03-31 23:34:45,332 - __main__ - INFO - Периодические задачи настроены
2025-03-31 23:34:45,332 - __main__ - INFO - Запуск бота в режиме long polling
2025-03-31 23:34:49,789 - __main__ - INFO - Команда /start от пользователя Al (ID: 847964518)
2025-03-31 23:34:49,938 - __main__ - INFO - Отправлено приветственное сообщение пользователю 847964518
2025-03-31 23:34:52,228 - __main__ - INFO - Callback от пользователя Al (ID: 847964518): info
2025-03-31 23:34:52,409 - __main__ - INFO - Отправлена информация о боте пользователю 847964518
2025-03-31 23:34:53,529 - __main__ - INFO - Callback от пользователя Al (ID: 847964518): test
2025-03-31 23:34:53,690 - __main__ - INFO - Отправлено тестовое сообщение пользователю 847964518
2025-03-31 23:34:54,851 - __main__ - INFO - Callback от пользователя Al (ID: 847964518): menu
2025-03-31 23:34:55,047 - __main__ - INFO - Пользователь 847964518 вернулся в главное меню
2025-03-31 23:34:55,332 - __main__ - ERROR - Ошибка при проверке соединения: 'coroutine' object has no attribute 'first_name'
2025-03-31 23:34:55,340 - __main__ - ERROR - Ошибка при обработке обновления: object NoneType can't be used in 'await' expression
2025-03-31 23:34:56,291 - __main__ - INFO - Callback от пользователя Al (ID: 847964518): info
2025-03-31 23:34:56,487 - __main__ - INFO - Отправлена информация о боте пользователю 847964518
2025-03-31 23:34:57,461 - __main__ - INFO - Callback от пользователя Al (ID: 847964518): test
2025-03-31 23:34:57,637 - __main__ - INFO - Отправлено тестовое сообщение пользователю 847964518
2025-03-31 23:34:58,803 - __main__ - INFO - Callback от пользователя Al (ID: 847964518): menu
2025-03-31 23:34:58,974 - __main__ - INFO - Пользователь 847964518 вернулся в главное меню
2025-03-31 23:35:45,337 - __main__ - INFO - Бот работает. Время работы: 60.25 сек.
2025-03-31 23:35:45,337 - __main__ - ERROR - Ошибка при обработке обновления: object NoneType can't be used in 'await' expression
2025-03-31 23:35:55,333 - __main__ - ERROR - Ошибка при проверке соединения: 'coroutine' object has no attribute 'first_name'
2025-03-31 23:35:55,333 - __main__ - ERROR - Ошибка при обработке обновления: object NoneType can't be used in 'await' expression
2025-03-31 23:36:38,536 - __main__ - INFO - Callback от пользователя Al (ID: 847964518): test
2025-03-31 23:36:38,866 - __main__ - INFO - Отправлено тестовое сообщение пользователю 847964518
2025-03-31 23:36:40,055 - __main__ - INFO - Callback от пользователя Al (ID: 847964518): menu
2025-03-31 23:36:40,247 - __main__ - INFO - Пользователь 847964518 вернулся в главное меню
2025-03-31 23:36:41,389 - __main__ - INFO - Callback от пользователя Al (ID: 847964518): test
2025-03-31 23:36:41,713 - __main__ - INFO - Отправлено тестовое сообщение пользователю 847964518
2025-03-31 23:36:45,194 - __main__ - INFO - Сообщение от пользователя Al (ID: 847964518): Пррп
2025-03-31 23:36:45,308 - __main__ - INFO - Отправлен эхо-ответ пользователю 847964518
2025-03-31 23:36:47,957 - __main__ - INFO - Callback от пользователя Al (ID: 847964518): menu
2025-03-31 23:36:48,126 - __main__ - INFO - Пользователь 847964518 вернулся в главное меню
2025-03-31 23:36:50,546 - __main__ - INFO - Callback от пользователя Al (ID: 847964518): info
2025-03-31 23:36:50,933 - __main__ - INFO - Отправлена информация о боте пользователю 847964518
2025-03-31 23:36:55,334 - __main__ - ERROR - Ошибка при проверке соединения: 'coroutine' object has no attribute 'first_name'
2025-03-31 23:36:55,334 - __main__ - ERROR - Ошибка при обработке обновления: object NoneType can't be used in 'await' expression
2025-03-31 23:37:55,334 - __main__ - ERROR - Ошибка при проверке соединения: 'coroutine' object has no attribute 'first_name'
2025-03-31 23:37:55,334 - __main__ - ERROR - Ошибка при обработке обновления: object NoneType can't be used in 'await' expression
2025-03-31 23:38:55,334 - __main__ - ERROR - Ошибка при проверке соединения: 'coroutine' object has no attribute 'first_name'
2025-03-31 23:38:55,335 - __main__ - ERROR - Ошибка при обработке обновления: object NoneType can't be used in 'await' expression
2025-03-31 23:39:12,243 - __main__ - INFO - Callback от пользователя Al (ID: 847964518): test
2025-03-31 23:39:12,601 - __main__ - INFO - Отправлено тестовое сообщение пользователю 847964518
2025-03-31 23:39:13,676 - __main__ - INFO - Callback от пользователя Al (ID: 847964518): menu
2025-03-31 23:39:13,842 - __main__ - INFO - Пользователь 847964518 вернулся в главное меню
2025-03-31 23:39:15,007 - __main__ - INFO - Callback от пользователя Al (ID: 847964518): test
2025-03-31 23:39:15,202 - __main__ - INFO - Отправлено тестовое сообщение пользователю 847964518
2025-03-31 23:39:18,182 - __main__ - INFO - Callback от пользователя Al (ID: 847964518): info
2025-03-31 23:39:18,404 - __main__ - INFO - Отправлена информация о боте пользователю 847964518
2025-03-31 23:39:21,358 - __main__ - INFO - Команда /start от пользователя Al (ID: 847964518)
2025-03-31 23:39:21,490 - __main__ - INFO - Отправлено приветственное сообщение пользователю 847964518
2025-03-31 23:39:23,097 - __main__ - INFO - Callback от пользователя Al (ID: 847964518): info
2025-03-31 23:39:23,313 - __main__ - INFO - Отправлена информация о боте пользователю 847964518
2025-03-31 23:39:55,334 - __main__ - ERROR - Ошибка при проверке соединения: 'coroutine' object has no attribute 'first_name'
2025-03-31 23:39:55,336 - __main__ - ERROR - Ошибка при обработке обновления: object NoneType can't be used in 'await' expression
